### ISSUE TITLE
JSON-LD parsing

### ISSUE THREAD

**Issue by EmidioStani** [zazuko/rdf-converter#25]
Hello,

I wanted to use the converter on this example:

https://www.w3.org/TR/json-ld/#example-20-describing-disconnected-nodes-with-graph

to generate a Turtle format.

However it does not generate and I can see an error in the browse dev tools:
Error: Invlalid prefix id for text/turtle RDF serialization format: '0'

It seems the array in the context is not supported.

Cheers,

**Comment by tpluscode** [comment]
Will have a look. The issue is actually with serialization.

**Comment by tpluscode** [comment]
Ah, you were right after all. The problem is with `@rdfjs/parser-jsonld`: https://github.com/rdfjs-base/parser-jsonld/issues/19
