### ISSUE TITLE
Support for text/plain for remote context in JSON-LD

### ISSUE THREAD

**Issue by EmidioStani** [zazuko/rdf-converter#34]
Hello,

I was testing the below example:

{
  "@context": "https://raw.githubusercontent.com/SEMICeu/DCAT-AP/master/releases/3.0.0/html/examples/context.jsonld",
  "@graph": [
    {
      "@id": "example-ds:BeePopulation",
      "@type": "Dataset",
      "description": {
        "en": "A dataset about bee population in Greece"
      },
      "publisher": "example-ag:GreekEnvironmentAgency",
      "title": {
        "en": "Bee population"
      }
    }
  ]
}

but I get parsing error as the remote context is passed in text/plain. Would it be possible to add it text/plain for json-ld ?

Thanks,

Emidio

**Comment by tpluscode** [comment]
Internally, the parsing is done by [jsonld-streaming-parser](https://github.com/rubensworks/jsonld-streaming-parser.js)

I would suggest to ask there first. 

While it could be possible to overcome, I will close here for now. I find this problem not exactly within the scope of the converter app. If you feel like no solutions on the lower level are possible, please feel free to reopen and we'll see what can be done
