### ISSUE TITLE
support for @base

### ISSUE THREAD

**Issue by EmidioStani** [zazuko/rdf-converter#36]
Hello,

I wanted to use the converter on the example: 

https://www.w3.org/TR/json-ld11/#example-28-setting-the-document-base-in-a-document

If paste it in the converter, I see this in the console :

 Error: Invlalid prefix id for text/turtle RDF serialization format: '@base'

is the @base supported in the parsing or it is a problem in serializing ?

**Comment by tpluscode** [comment]
Ah, this is another case of context being incorrectly interpreted as prefixes, as reported earlier in #31 

Will integrate a patch momentarily
